//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Net.Security;

namespace ConsoleApp1.ServiceReference1 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inti.notariado.org/XML")]
    public partial class ServiceDispatcherException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string infoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("info");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://inti.notariado.org/XML", 
        ProtectionLevel = ProtectionLevel.Sign,
        ConfigurationName="ServiceReference1.ServiceDispatcher")]
    public interface ServiceDispatcher {
        
        // CODEGEN: Generating message contract since the operation process is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApp1.ServiceReference1.ServiceDispatcherException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApp1.ServiceReference1.processResponse process(ConsoleApp1.ServiceReference1.processRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.processResponse> processAsync(ConsoleApp1.ServiceReference1.processRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://inti.notariado.org/XML")]
    public partial class SERVICE_DISPATCHER : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime tIMESTAMPField;
        
        private sbyte tIPO_MSJField;
        
        private string eMISORField;
        
        private string rECEPField;
        
        private string cUVField;
        
        private string sERVICIOField;
        
        private GENERADORType gENERADORField;
        
        public SERVICE_DISPATCHER() {
            this.rECEPField = "CGN";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime TIMESTAMP {
            get {
                return this.tIMESTAMPField;
            }
            set {
                this.tIMESTAMPField = value;
                this.RaisePropertyChanged("TIMESTAMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public sbyte TIPO_MSJ {
            get {
                return this.tIPO_MSJField;
            }
            set {
                this.tIPO_MSJField = value;
                this.RaisePropertyChanged("TIPO_MSJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EMISOR {
            get {
                return this.eMISORField;
            }
            set {
                this.eMISORField = value;
                this.RaisePropertyChanged("EMISOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RECEP {
            get {
                return this.rECEPField;
            }
            set {
                this.rECEPField = value;
                this.RaisePropertyChanged("RECEP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CUV {
            get {
                return this.cUVField;
            }
            set {
                this.cUVField = value;
                this.RaisePropertyChanged("CUV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SERVICIO {
            get {
                return this.sERVICIOField;
            }
            set {
                this.sERVICIOField = value;
                this.RaisePropertyChanged("SERVICIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public GENERADORType GENERADOR {
            get {
                return this.gENERADORField;
            }
            set {
                this.gENERADORField = value;
                this.RaisePropertyChanged("GENERADOR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inti.notariado.org/XML")]
    public partial class GENERADORType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nOMBRE_PROVEEDORField;
        
        private string nOMBRE_APLICACIONField;
        
        private string vERSION_APLICACIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NOMBRE_PROVEEDOR {
            get {
                return this.nOMBRE_PROVEEDORField;
            }
            set {
                this.nOMBRE_PROVEEDORField = value;
                this.RaisePropertyChanged("NOMBRE_PROVEEDOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NOMBRE_APLICACION {
            get {
                return this.nOMBRE_APLICACIONField;
            }
            set {
                this.nOMBRE_APLICACIONField = value;
                this.RaisePropertyChanged("NOMBRE_APLICACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string VERSION_APLICACION {
            get {
                return this.vERSION_APLICACIONField;
            }
            set {
                this.vERSION_APLICACIONField = value;
                this.RaisePropertyChanged("VERSION_APLICACION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://inti.notariado.org/XML")]
        public ConsoleApp1.ServiceReference1.SERVICE_DISPATCHER SERVICE_DISPATCHER;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inti.notariado.org/XML", Order=0)]
        public System.Xml.XmlElement SERVICE_DISPATCHER_REQUEST;
        
        public processRequest() {
        }
        
        public processRequest(ConsoleApp1.ServiceReference1.SERVICE_DISPATCHER SERVICE_DISPATCHER, System.Xml.XmlElement SERVICE_DISPATCHER_REQUEST) {
            this.SERVICE_DISPATCHER = SERVICE_DISPATCHER;
            this.SERVICE_DISPATCHER_REQUEST = SERVICE_DISPATCHER_REQUEST;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inti.notariado.org/XML", Order=0)]
        public System.Xml.XmlElement SERVICE_DISPATCHER_RESPONSE;
        
        public processResponse() {
        }
        
        public processResponse(System.Xml.XmlElement SERVICE_DISPATCHER_RESPONSE) {
            this.SERVICE_DISPATCHER_RESPONSE = SERVICE_DISPATCHER_RESPONSE;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceDispatcherChannel : ConsoleApp1.ServiceReference1.ServiceDispatcher, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDispatcherClient : System.ServiceModel.ClientBase<ConsoleApp1.ServiceReference1.ServiceDispatcher>, ConsoleApp1.ServiceReference1.ServiceDispatcher {
        
        public ServiceDispatcherClient() {
        }
        
        public ServiceDispatcherClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDispatcherClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDispatcherClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDispatcherClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.ServiceReference1.processResponse ConsoleApp1.ServiceReference1.ServiceDispatcher.process(ConsoleApp1.ServiceReference1.processRequest request) {
            return base.Channel.process(request);
        }
        
        public System.Xml.XmlElement process(ConsoleApp1.ServiceReference1.SERVICE_DISPATCHER SERVICE_DISPATCHER, System.Xml.XmlElement SERVICE_DISPATCHER_REQUEST) {
            ConsoleApp1.ServiceReference1.processRequest inValue = new ConsoleApp1.ServiceReference1.processRequest();
            inValue.SERVICE_DISPATCHER = SERVICE_DISPATCHER;
            inValue.SERVICE_DISPATCHER_REQUEST = SERVICE_DISPATCHER_REQUEST;
            ConsoleApp1.ServiceReference1.processResponse retVal = ((ConsoleApp1.ServiceReference1.ServiceDispatcher)(this)).process(inValue);
            return retVal.SERVICE_DISPATCHER_RESPONSE;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.processResponse> ConsoleApp1.ServiceReference1.ServiceDispatcher.processAsync(ConsoleApp1.ServiceReference1.processRequest request) {
            return base.Channel.processAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.processResponse> processAsync(ConsoleApp1.ServiceReference1.SERVICE_DISPATCHER SERVICE_DISPATCHER, System.Xml.XmlElement SERVICE_DISPATCHER_REQUEST) {
            ConsoleApp1.ServiceReference1.processRequest inValue = new ConsoleApp1.ServiceReference1.processRequest();
            inValue.SERVICE_DISPATCHER = SERVICE_DISPATCHER;
            inValue.SERVICE_DISPATCHER_REQUEST = SERVICE_DISPATCHER_REQUEST;
            return ((ConsoleApp1.ServiceReference1.ServiceDispatcher)(this)).processAsync(inValue);
        }
    }
}
